In [1]:
# 导包
import numpy as np

In [8]:
# n维数组ndarray， 描述存储一组相同类型的数据
array1 = np.array([1,2,3,4,5,6])
# 3行4列二维
array2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
# 三维度 类比range
array3 = np.arange(30).reshape(2,3,5)

In [18]:
# 指定dtype
array4 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]],dtype=np.float64)

In [22]:
# astype转换ndarray的数据类型
np.arange(30).reshape(2,3,5).astype(np.float32)

array([[[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.]],

       [[15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24.],
        [25., 26., 27., 28., 29.]]], dtype=float32)

In [20]:
array4.dtype

dtype('float64')

In [10]:
# 获取ndarray的维度
array3.ndim

3

In [11]:
# 元素个数
array3.size

30

In [15]:
# ndarray的形状，是一个元组，(每个维度的元素个数)
array2.shape

(3, 4)

In [16]:
# 元素的数据类型 np.int
array3.dtype

dtype('int32')

In [17]:
# 元素占用的内存空间大小，单位字节
array3.itemsize

4

In [27]:
# 创建全为1的ndarray, 可以使用dtype指定数据类型
np.ones(40, dtype=np.int16).reshape(5,8)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]], dtype=int16)

In [29]:
# 创建全为0的ndarray
np.zeros(30, dtype=np.int64).reshape(5,6)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int64)

In [28]:
# 创建一个不指定初始值的ndarray
np.empty(20,dtype=np.int16)

array([257, 257, 257, 257, 257, 257, 257, 257, 257, 257, 257, 257, 257,
       257, 257, 257, 257, 257, 257, 257], dtype=int16)

In [31]:
#创建ndarray常用方式
#np.array([])  arange(start,end,step), end不包括
np.arange(10,100,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

### ndarray的运算

In [46]:
# 两个相同形状的ndarry直接的算术运算, 规则，对用位置的元素进行算数运算
array4 = np.arange(10)
array5 = np.arange(0,10)

In [42]:
array4 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
array5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
array5 / array4

<ipython-input-48-5af784ab650e>:1: RuntimeWarning: invalid value encountered in true_divide
  array5 / array4


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [49]:
# ndarray和标量之间运算， 每个元素都和该标量进行运算
array4 + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
# 广播机制
# 可以广播的条件：
# 1：相同维度下，不同形状的2个ndarray要成功广播，需满足，对应维度的元素个数要么相等，要么其中一个为1
# 2：不同维度下，先将形状的元组进行右对齐，重叠部分的维度，满足条件1，即可
# (4,5,8)
#   (5,1)
array4 = np.arange(12).reshape(3,4)
array5 = np.arange(4).reshape(1,4)
array6 = np.arange(3).reshape(3,1)
array7 = np.arange(6).reshape(3,2)
array8 = np.arange(160).reshape(4,5,8)
array9 = np.arange(5).reshape(5,1) # 广播过程-> (5,8) ->(1,5,8) ->(4,5,8)

In [62]:
array8

array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31],
        [ 32,  33,  34,  35,  36,  37,  38,  39]],

       [[ 40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60,  61,  62,  63],
        [ 64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79]],

       [[ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 88,  89,  90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111],
        [112, 113, 114, 115, 116, 117, 118, 119]],

       [[120, 121, 122, 123, 124, 125, 126, 127],
        [128, 129, 130, 131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140, 141, 142, 143],
        [144, 145, 146, 147, 148, 149, 150, 151],
        [152, 153, 154, 155, 156, 157, 158, 

In [63]:
array8+ array9

array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  9,  10,  11,  12,  13,  14,  15,  16],
        [ 18,  19,  20,  21,  22,  23,  24,  25],
        [ 27,  28,  29,  30,  31,  32,  33,  34],
        [ 36,  37,  38,  39,  40,  41,  42,  43]],

       [[ 40,  41,  42,  43,  44,  45,  46,  47],
        [ 49,  50,  51,  52,  53,  54,  55,  56],
        [ 58,  59,  60,  61,  62,  63,  64,  65],
        [ 67,  68,  69,  70,  71,  72,  73,  74],
        [ 76,  77,  78,  79,  80,  81,  82,  83]],

       [[ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 89,  90,  91,  92,  93,  94,  95,  96],
        [ 98,  99, 100, 101, 102, 103, 104, 105],
        [107, 108, 109, 110, 111, 112, 113, 114],
        [116, 117, 118, 119, 120, 121, 122, 123]],

       [[120, 121, 122, 123, 124, 125, 126, 127],
        [129, 130, 131, 132, 133, 134, 135, 136],
        [138, 139, 140, 141, 142, 143, 144, 145],
        [147, 148, 149, 150, 151, 152, 153, 154],
        [156, 157, 158, 159, 160, 161, 162, 

In [59]:
array4 + array7

ValueError: operands could not be broadcast together with shapes (3,4) (3,2) 

### ndarray的索引

In [67]:
array4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [68]:
# 基本索引方式 ndarray[第1个维度的序号,第2维度的序号,...,第n个维度的序号]
# 通过序号来索引，从0开始
array4[1,3]

7

In [69]:
# 索引第一个维度的元素，索引第1行
array4[1]

array([4, 5, 6, 7])

In [75]:
# 切片方式   start:end:step, 可以针对任意一个维度
array4[:1,1:3]

array([[1, 2]])

In [76]:
# 花式索引 ndarray[第一个维度的序号列表,第二个维度的序号列表,...,第n个维度的序号列表]
# 0行1列元素，和2行3列的元素
# 对比切片方式，使用的序号是不连续的
array4[[0,2],[1,3]]

array([1, 7])

In [77]:
# 返回array4的4个角的元素，返回一个新的一维的ndarray
array4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [78]:
array4[[0,0,2,2],[0,3,0,3]]

array([ 0,  3,  8, 11])

In [79]:
# 返回array4的4个角的元素，返回一个新的二维的2行2列的ndarray,了解
array4[[[0,0],[2,2]],[[0,3],[0,3]]]

array([[ 0,  3],
       [ 8, 11]])

In [83]:
#布尔索引
# 布尔数组： 元素类型为bool的ndarray
# ndarray做比较运算 > < >= <= != ==
bool_array = array4 > 9

In [84]:
# 定义：使用布尔数组进行索引, 使用场景，就是做元素的条件筛选

array4[bool_array]

array([10, 11])

In [85]:
array4[array4<5]

array([0, 1, 2, 3, 4])

In [87]:
# 筛选5到9之间的元素  : 逻辑运算符 都可以操作bool数组，& | ~
bool_array = (array4 > 5) & (array4 < 9)

In [89]:
array4[bool_array]

array([6, 7, 8])

### 深拷贝和浅拷贝

In [90]:
# 深拷贝：集合里面的元素进行完整的复制了一份
# 浅拷贝：仅对集合对象进行复制，集合里面的元素仍然是之前
# python的列表的切片操作是深拷贝
# ndarray的切片操作是浅拷贝
list1 = [1,2,3,4,5]
list2 = list1[:]


In [91]:
#修改切片后的list2的元素值，不会影响list1的元素内容
list2[0] = 100

In [95]:
array10 = array4[:,2]

In [97]:
# 修改索引后的ndarray的元素值，会影响原ndarray
array10[0] = 100

In [98]:
array4

array([[  0,   1, 100,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

### 通用函数

In [99]:
# 一元函数 ：操作一个ndarray，np.floor(ndarray)
# 二原函数: 操作二个ndarray，np.add(ndarray1,ndarray2)
# 一元函数：
array6 = np.array([1.3,2.4,3.6,5.1])
# 向上取整：取大于该浮点数的最小的整数
np.ceil(array6)

array([2., 3., 4., 6.])

In [100]:
#向下取整：取小于该浮点数的最大的整数
np.floor(array6)

array([1., 2., 3., 5.])

In [ ]:
# 二元函数
# ndarray之间加减乘除 add(),subtract()等, 等价于 + - * /算术运算符
# greater() less()等 ,等价于> < >= <= != ==比较运算符

In [103]:
# java 三元操作符 条件表达式?表达式1:表达式2
# numpy提供一个numpy版本"三元操作符"： 
# where(布尔数组，ndarray1，ndarray2)，根据布尔数组里元素的真假，真就取ndarray1的元素，假就取ndarray2的元素
# 返回一个同样形状的新的ndarray
# 把array4大于10的数置0
np.where(array4>10, 0, array4)

array([[ 0,  1,  0,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10,  0]])

In [105]:
# 把array4等于0的元素置为1
np.where(array4==0, 1, array4)

array([[  1,   1, 100,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [106]:
# 统计计算函数
# 聚合函数: 一组数统计计算成一个数
# 求和sum() 求最大值max()，求最小值min(), 求mean()平均值，求最大值序号argmax()....求累积和cussum()
array6 = np.array([1,2,3,4])

In [108]:
# numpy函数
np.max(array6)

4

In [110]:
#ndarray对象的方法
array6.max()

3

In [113]:
array4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [116]:
# np.any(布尔ndarray)
# 布尔ndarray中只要有一个True，返回True
if np.any(array4 >11):
    print("array4中至少有一个元素大于11")
else:
    print("array4中没有一个元素大于11")

array4中没有一个元素大于11


In [119]:
# np.all(布尔ndarray)
# 这个布尔ndarray中全部为True，返回True
# 只要有一个False，返回False
if np.all(array4>0):
    print("array4中的元素全部大于0")
else:
    print("array4中至少有一个元素小于等于0")


array4中至少有一个元素小于等于0


### 线性代数相关函数

In [123]:
# dot()点乘   matmul()矩阵乘法
# M * N 矩阵，N * L矩阵 矩阵乘法 -> M * L
#创建5个同学的平时成绩和考试成绩 5行2列
array8 = np.array([[60,90],[70,70],[100,80],[90,60],[50,60]])
#系数矩阵为2行1列
factor_array = np.array([[0.3],[0.7]])
# 做矩阵乘积计算最终成绩
np.matmul(array8, factor_array)

array([[81.],
       [70.],
       [86.],
       [69.],
       [57.]])

In [121]:
array8

array([[ 60,  90],
       [ 70,  70],
       [100,  80],
       [ 90,  60],
       [ 50,  60]])

### 随机数模块

In [124]:
# 使用随机数模块来生成ndarray
# array() arange() ones() zeros() empty()都可以创建ndarray
# 随机生成20个一维的值在[0,1)区间中的浮点数
np.random.rand(20).reshape(4,5)


array([0.0438619 , 0.45642095, 0.13862138, 0.74136346, 0.85854348,
       0.3622459 , 0.023417  , 0.37450558, 0.67582853, 0.2299648 ,
       0.47318297, 0.16937854, 0.71082537, 0.33069867, 0.89064105,
       0.99667143, 0.21468895, 0.25851506, 0.45568117, 0.04884311])

In [125]:
# 生成40至100之间，30个随机整数
np.random.randint(40,100,30).reshape(15,2)

array([[56, 43],
       [47, 76],
       [55, 96],
       [74, 40],
       [47, 67],
       [50, 40],
       [51, 54],
       [86, 67],
       [41, 85],
       [67, 45],
       [48, 96],
       [58, 47],
       [89, 49],
       [78, 79],
       [81, 45]])

In [127]:
# 生成随机的[0,1)区间的20个符合平均分布的浮点数
np.random.uniform(0,1, 20)

array([0.45894193, 0.5866759 , 0.27926281, 0.84624581, 0.08104467,
       0.99088216, 0.70007636, 0.74798237, 0.59727057, 0.51142411,
       0.17259404, 0.45084663, 0.3895702 , 0.2451004 , 0.24954466,
       0.00975887, 0.59780538, 0.15349179, 0.23162728, 0.63294733])

In [154]:
# 生成的为期望值为0，标准差为1的200个符合正态分布规律的随机浮点数
array9 = np.random.normal(0,1, 200)
# 看array9中有没有大于3的数，有就筛选出来
array9[array9 > 3]

array([], dtype=float64)

In [155]:
# 酒鬼漫步：模拟酒鬼漫步：在一条线上随机的向前或向后移动2000步，计算这2000步中，向前最远走到多少米，
#（一步0.5米），向后最远走到多少米；走到15米时（不论前后），走了多少步？

In [184]:
# 生成2000的随机的+1和-1的ndarray来模拟酒鬼移动情况
random_array = np.random.rand(2000) # 生成[0,1)区间的随机数
random_steps = np.where(random_array >= 0.5,1,-1) 
# 累积走了n步之后移动的距离，2000个元素的ndarray
random_distence = np.cumsum(random_steps * 0.5)
# 对random_distence求极值
max_distence = np.max(random_distence)
min_distence = np.min(random_distence)
print("max_distence=" + str(max_distence) + ", min_distence=" + str(min_distence))
#计算酒鬼移动的距离数组中，绝对值第一个大于等于15的索引序号，即走了多少步
step_index = np.argmax(np.abs(random_distence) >= 15)
print("走到15米时（不论前后），走了" + str(step_index) + "步")

max_distence=10.5, min_distence=-10.0
走到15米时（不论前后），走了0步


In [175]:
# argmax最大值的索引，第一个True所在索引值，就是正向走到15米时，走了多少步
np.argmax(random_distence >= 15)

array([False, False, False, ...,  True,  True,  True])

In [ ]:
#第一个True所在索引值，就是向后走到15米时，走了多少步
np.argmax(random_distence <= -15)

In [ ]:
#累积和统计计算
# [1,2,3,4] -> [1,1+2,1+2+3,1+2+3+4]

In [ ]:
# 练习： 随机生成10个同学语文、数学，英语3门成绩
# 求前5个同学的语文平均成绩
# 求前5个同学的数学最高成绩
# 求前5个同学的英语最低成绩

In [185]:
import random

In [186]:
# %time魔法指令，可以统计代码的运行时间
# 统计1000万个随机浮点数，求和所花费的时间
# numpy的ndarray相关运算速度比python list快
list1 = []
size = 10000000
for x in range(size):
    list1.append(random.random()) #[0,1)区间浮点数


In [188]:
ndarray1 = np.random.rand(size)

In [199]:
%time sum(list1)

Wall time: 108 ms


5000917.9915966615

In [196]:
%time np.sum(ndarray1)

Wall time: 15 ms


4999857.050637804